# Generated by Django 4.0.2 on 2022-02-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='background.png', null=True, upload_to='posts_pic'),
        ),
    ]
