# Generated by Django 4.1.6 on 2023-03-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_newsletter_subscribe_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='timestamp',
            new_name='comment_date',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(default='2023-03-20 13:37:58'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='subscribe_date',
            field=models.DateTimeField(default='2023-03-20 13:37:58'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default='2023-03-20 13:37:58'),
        ),
    ]
