# Generated by Django 4.1.6 on 2023-03-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_contact_contact_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(default='2023-03-20 13:48:07'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='subscribe_date',
            field=models.DateTimeField(default='2023-03-20 13:48:07'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default='2023-03-20 13:48:07'),
        ),
    ]
